name: Play with various flow activation methods

on:
  # To trigger the Env Test workflow manually, follow the instructions in
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - error
        - warning
        - debug
      gitTag:
        description: 'Git tag at which to sync'
        type: string
      gitRepeatBuildTag:
        description: 'Timestamp to use for repeatable builds'
        required: false
        type: string
      releaseAct:
        description: 'Create and post to release'
        required: false
        type: boolean
      releaseTag:
        description: 'Tag used to create a release / post to it'
        type: string

permissions: write-all

jobs:
  test_releasing:
    runs-on: ubuntu-latest

    steps:
      - name: Show environment
        run: |
          echo "==============================" > report.log
          echo "Log level   : $LEVEL" >> report.log
          echo "ReleaseAct  : $DO_RELEASE" >> report.log
          echo "git tag     : $GIT_TAG" >> report.log
          echo "Timestamp   : $TIME_STAMP" >> report.log
          echo "Environment : ${{ inputs.environment }}" >> report.log
          echo "GITHUB_SHA  : ${GITHUB_SHA}" >> report.log
          echo "GITHUB_REF  : ${GITHUB_REF}" >> report.log
          echo "==============================" >> report.log
          set >> report.log
          zip report.zip report.log
        env:
          LEVEL: ${{ inputs.logLevel }}
          DO_RELEASE: ${{ inputs.releaseAct }}
          GIT_TAG: ${{ inputs.gitTag }}
          TIME_STAMP: ${{ inputs.gitRepeatBuildTag }}
      - name: Try gh, see if available and works after release
        if: ${{ inputs.releaseAct && startsWith(inputs.releaseTag, 'releaseDraft') }}
        run: |
          echo "=============================="
          gh --help
          echo "=============================="          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.releaseTag }}
          release_name: Release ${{ inputs.releaseTag }}
          body: |
            Unicode® ICU 76 updates to CLDR 46 (beta blog) locale data with new locales and various additions and corrections.
            C++ code now requires C++17 and is being made more robust.

            Also includes Unicode 16.0.0 data.

            For details, please see https://icu.unicode.org/download/76.

            A list:
              - item 1
              - item 2
              - item 3
            And a table:
              | Heading 1 | Heading 2 | Heading 3 |
              | --------- | --------- | --------- |
              | cel 1.1   | cel 1.2   | cel 1.3   |
              | cel 2.1   | cel 2.2   | cel 2.3   |              
          draft: true
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./report.zip
          asset_name: report.zip
          asset_content_type: application/zip     

  test_releasing_with_gh:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment
        run: |
          set >> report2.log
          zip report2.zip report2.log
      - name: List releases with gh
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${OWNER}/${REPO}/releases
      - name: Create release with gh
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${OWNER}/${REPO}/releases \
          -f "tag_name=v1.0.0" -f "target_commitish=master" -f "name=v1.0.0" -f "body=Description of the release" -F "draft=true" -F "prerelease=false" -F "generate_release_notes=false"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
