name: Play with various flow activation methods

on:
  # To trigger the Env Test workflow manually, follow the instructions in
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - error
        - warning
        - debug
      gitTag:
        description: 'Git tag at which to sync'
        type: string
      gitRepeatBuildTag:
        description: 'Timestamp to use for repeatable builds'
        required: false
        type: string
      releaseAct:
        description: 'Create and post to release'
        required: false
        type: boolean
      releaseTag:
        description: 'Tag used to create a release / post to it'
        type: string

# permissions: write-all
permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.event.repository.name }}


jobs:
  test_releasing:
    runs-on: ubuntu-latest

    steps:

      - name: Show environment
        run: |
          echo "==============================" > report.log
          echo "Log level   : $LEVEL" >> report.log
          echo "ReleaseAct  : $DO_RELEASE" >> report.log
          echo "git tag     : $GIT_TAG" >> report.log
          echo "Timestamp   : $TIME_STAMP" >> report.log
          echo "Environment : ${{ inputs.environment }}" >> report.log
          echo "GITHUB_SHA  : ${GITHUB_SHA}" >> report.log
          echo "GITHUB_REF  : ${GITHUB_REF}" >> report.log
          echo "==============================" >> report.log
          set >> report.log
          zip report.zip report.log
        env:
          LEVEL: ${{ inputs.logLevel }}
          DO_RELEASE: ${{ inputs.releaseAct }}
          GIT_TAG: ${{ inputs.gitTag }}
          TIME_STAMP: ${{ inputs.gitRepeatBuildTag }}

      - name: Try gh, see if available and works after release
        if: ${{ inputs.releaseAct && startsWith(inputs.releaseTag, 'releaseDraft') }}
        run: |
          echo "=============================="
          gh --help
          echo "=============================="

      - name: Generate the body content
        run: |
          ls / > RELEASE.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.releaseTag }}
          release_name: Release ${{ inputs.releaseTag }}
          body_path: RELEASE.md
          draft: true
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./report.zip
          asset_name: report.zip
          asset_content_type: application/zip     

  test_releasing_with_gh:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment
        run: |
          set >> report2.log
          zip report2.zip report2.log
      - name: List releases with gh
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${OWNER}/${REPO}/releases
      - name: Create release with gh
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${OWNER}/${REPO}/releases \
          -f "tag_name=v1.0.0" -f "target_commitish=main" -f "name=v1.0.0" -f "body=Description of the release" -F "draft=true" -F "prerelease=false" -F "generate_release_notes=false"
      - name: Play with environ files, GITHUB_OUTPUT
        run: |
          echo "{name}={value}" >> "$GITHUB_OUTPUT"
      - name: Play with environ files, warning
        run: |
          echo "::debug::Set the Octocat variable"
          echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      - name: Play with environ files, group
        run: |
          echo "::group::My title"
          echo "Inside group"
          echo "Also inside group"
          echo "And again inside group"
          echo "::endgroup::"          
      - name: Play with environ files, GITHUB_STEP_SUMMARY
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
