name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
    - uses: actions/checkout@v4
      run: docker build . --file .github/Dockerfile_fedora --tag fedora-docker-icu:$(date +%s)
      
