name: Create and publish a Fedora Docker Image CI

on:
  workflow_dispatch:
    inputs:
      gitTag:
        description: 'Git tag at which to sync for deploy and release'
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file .github/Dockerfile_fedora --tag fedora-docker-icu:$(date --iso-8601)
