name: Build ICU4C on Fedora Linux

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'Something, whatever'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/mihnita/fedora-docker-gcr
    permissions:
      contents: read

    steps:

    - name: Inspect
      run: |
        echo $PWD \
        ls \
        ls /

    - name: Checkout repo files
      run: |
        git clone --depth=1 https://github.com/unicode-org/icu.git \

    - name: Build ICU4J
      run: |
        cd icu/icu4c/source \
        ./runConfigureICU Linux/gcc \
        make -j8 \
        make check \
        sed -i 's/^DOXYGEN *= *$/DOXYGEN = echo/g' Makefile \
        make dist
