name: Build ICU4C on Fedora Linux

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'Something, whatever'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/mihnita/fedora-docker-gcr:20240908
      credentials:
        username: ${{ secrets.DOCKER_CONTAINER_USER_NAME }}
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}

    permissions:
      contents: read

    steps:

    - name: Inspect
      run: |
        echo $PWD
        ls -ali /
        ls -ali
        cd
        echo $PWD
        ls -ali

    - name: Checkout repo files
      run: |
        git clone --depth=1 https://github.com/unicode-org/icu.git

    - name: Release ICU4J
      run: |
        pushd icu/icu4c/source
        ./runConfigureICU Linux/gcc
        make -j8
        sed -i 's/^DOXYGEN *= *$/DOXYGEN = echo/g' Makefile
        make doc
        make dist
        ls -al dist
        popd

    # TODO: add them to the GitHub "Release" page automatically
    - name: Upload build results
      uses: actions/upload-artifact@v4.3.6
      with:
        path: ./icu4j/${{ env.RELEASE_FOLDER }}/*
        retention-days: 3 # TBD if we want to keep them longer
        overwrite: true
