# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish to Nexus Sonatype OSS

on:
  release:
    types: [created]
  workflow_dispatch:
    # To trigger the Env Test workflow manually, follow the instructions in
    # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

env:
  SHARED_MVN_ARGS: '--show-version --no-transfer-progress'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repo files
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: |
        cd icu4j
        mvn ${SHARED_MVN_ARGS} -B clean package -P with_sources,with_javadoc

    - name: Publish to GitHub Packages Apache Maven
      run: |
        echo PWD=$PWD
        ls .
        ls /
        echo GITHUB_WORKSPACE = $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE
        env
        cd icu4j
        mvn deploy -s $GITHUB_WORKSPACE/settings.xml \
          -P with_sources,with_javadoc
      env:
        GITHUB_TOKEN: ${{ github.token }}
