name: Build ICU4C on Fedora and Ubuntu Linux

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'Release tag'
        type: string

jobs:

  build_fedora:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/fedora-docker-gcr:latest
      credentials:
        username: ${{ secrets.DOCKER_CONTAINER_USER_NAME }}
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
    - uses: ./.github/actions/release_icu4c
      with:
        distro: fedora

  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/release_icu4c
      with:
        distro: ubuntu
