name: Release - ICU4C artifacts on Fedora

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'Release tag'
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/fedora-docker-gcr:latest
      credentials:
        username: ${{ secrets.DOCKER_CONTAINER_USER_NAME }}
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}

    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout and setup
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Build release ICU4C
      run: |
        pushd icu4c/source
        ./runConfigureICU Linux/gcc
        make -j8
        # TODO: make check to make sure that what we publish works
        # make check
        make DESTDIR=/tmp/icu releaseDist
        make DESTDIR=$GITHUB_WORKSPACE/releaseDist/icu releaseDist
        popd

    - name: Collect artifacts in one folder
      run: |
        # Get the OS version in VERSION_ID
        source /etc/os-release
        # Get the ICU version in artifact_version
        source icu4j/releases_tools/shared.sh
        pushd releaseDist
        tar -czf icu4c-${artifact_version}-Fedora_Linux${VERSION_ID}-x64.tgz icu
        rm -fr icu
        popd

    # TODO: add them to the GitHub "Release" page automatically (on condition)
    - name: Upload build results
      uses: actions/upload-artifact@v4.3.6
      with:
        name: fedora-binaries
        path: ${{ github.workspace }}/releaseDist/
        retention-days: 3 # TBD if we want to keep them longer
        overwrite: true
