name: Release - ICU4C artifacts on Ubuntu

on:
  workflow_dispatch:
    inputs:
      gitTag:
        # TODO: make this mandatory and validate that it is in a release* branch and looks like
        # For now we don't do it so that we can test.
        description: 'Git tag at which to sync for deploy and release'
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release-env

    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout and setup
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install doxygen
      run: |
        sudo apt-get -y install doxygen

    - name: Build release ICU4C
      run: |
        pushd icu4c/source
        echo "==== runConfigureICU ===="
        ./runConfigureICU Linux/gcc
        echo "==== make ===="
        make -j8
        # TODO: make check to make sure that what we publish works
        # make check
        echo "==== make dist ===="
        make dist
        echo "==== make releaseDist ===="
        make DESTDIR=$GITHUB_WORKSPACE/releaseDist/icu releaseDist
        echo "=========================="
        popd

    - name: Collect artifacts in one folder
      run: |
        # Get the OS version in VERSION_ID
        source /etc/os-release
        # Get the ICU version in artifact_version
        source icu4j/releases_tools/shared.sh
        underscore_version=$(echo $artifact_version | sed 's/\./_/g')
        pushd releaseDist
        tar -czf icu4c-${underscore_version}-Ubuntu${VERSION_ID}-x64.tgz icu
        rm -fr icu
        popd
        mv icu4c/source/dist/icu4c-76_1-d*    releaseDist/
        mv icu4c/source/dist/icu4c-76_1-src.* releaseDist/

    # TODO: add them to the GitHub "Release" page automatically (on condition)
    - name: Upload build results
      uses: actions/upload-artifact@v4.3.6
      with:
        name: icu4c-ubuntu-binaries
        path: ${{ github.workspace }}/releaseDist/
        retention-days: 3 # TBD if we want to keep them longer
        overwrite: true
