name: Release - ICU4C artifacts on Ubuntu

on:
  workflow_dispatch:
    inputs:
      runTests:
        description: 'Run the tests.'
        type: boolean
        default: true
      gitReleaseTag:
        description: 'Release tag to upload to. Must start with "release-"'
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release-env

    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout and setup
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install doxygen
      run: |
        sudo apt-get -y install doxygen

    - name: Build release ICU4C
      run: |
        pushd icu4c/source
        #tmp ./runConfigureICU Linux/gcc
        # make -j8
        echo SPY on SKIP_TESTS = $SKIP_TESTS
        if [ $SKIP_TESTS = "true" ]; then
          echo SKIPPING TESTS
        else
          #tmp make check
          echo RUNNING TESTS
        fi
        #tmp make dist
        #tmp make DESTDIR=$GITHUB_WORKSPACE/releaseDist/icu releaseDist
        popd
      env:
        SKIP_TESTS: ${{ inputs.skipTests }}
        GIT_TAG: ${{ inputs.gitTag }}

    - name: Collect artifacts in one folder
      run: |
        # Get the OS version in VERSION_ID
        source /etc/os-release
        # Get the ICU version in artifact_version
        source icu4j/releases_tools/shared.sh
        # Convert 76.1 to 76_1
        underscore_version=$(echo $artifact_version | sed 's/\./_/g')
        pushd releaseDist
        tar -czf icu4c-${underscore_version}-Ubuntu${VERSION_ID}-x64.tgz icu
        rm -fr icu
        popd
        mv icu4c/source/dist/icu4c-76_1-d*    releaseDist/
        mv icu4c/source/dist/icu4c-76_1-src.* releaseDist/

    # TODO: add them to the GitHub "Release" page automatically (on condition)
    - name: Upload build results
      uses: actions/upload-artifact@v4.3.6
      with:
        name: icu4c-ubuntu-binaries
        path: ${{ github.workspace }}/releaseDist/
        retention-days: 3 # TBD if we want to keep them longer
        overwrite: true
