name: Build ICU4C on Fedora and Ubuntu Linux

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'Release tag'
        type: string

jobs:
  build_linux:

    strategy:
      fail-fast: false
      matrix:
        os:  [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    container:
      image: ghcr.io/${{ github.repository_owner }}/fedora-docker-gcr:latest
      credentials:
        username: ${{ secrets.DOCKER_CONTAINER_USER_NAME }}
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}

    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout and setup
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Build release ICU4C
      run: |
        source /etc/os-release
        source icu4j/releases_tools/shared.sh
        set
        set >> env.log
        cat /etc/os-release >> os.log
        tar czf icu4c-${artifact_version}-Fedora_Linux${VERSION_ID}-x64.tgz *.log

    # TODO: add them to the GitHub "Release" page automatically (on condition)
    - name: Upload build results
      uses: actions/upload-artifact@v4.3.6
      with:
        name: binaries
        path: ${{ github.workspace }}/icu4c-*.tgz
        retention-days: 3 # TBD if we want to keep them longer
        overwrite: true
