name: A - Test Conditions

on:
  workflow_dispatch:
    inputs:
      skipTests:
        description: 'Skip running the tests.'
        type: boolean
        default: false
      deployToMaven:
        description: 'Deploy to maven'
        type: boolean
        required: true
      gitReleaseTag:
        description: 'Release tag to upload to. Must start with "release-"'
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release-env

    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout and setup
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Show input
      run: |
        echo "=============================="
        echo "SKIP_TESTS      : $SKIP_TESTS"
        echo "DEPLOY_TO_MAVEN : $DEPLOY_TO_MAVEN"
        echo "GIT_RELEASE_TAG : $GIT_RELEASE_TAG"
        echo "env.SKIP_TESTS      : ${{ env.SKIP_TESTS }}"
        echo "env.DEPLOY_TO_MAVEN : ${{ env.DEPLOY_TO_MAVEN }}"
        echo "env.GIT_RELEASE_TAG : ${{ env.GIT_RELEASE_TAG }}"
        echo "input skipTests     : ${{ inputs.skipTests }}"
        echo "input deployToMaven : ${{ inputs.deployToMaven }}"
        echo "input gitReleaseTag : ${{ inputs.gitReleaseTag }}"
        echo "GITHUB_SHA  : ${GITHUB_SHA}"
        echo "GITHUB_REF  : ${GITHUB_REF}"
        echo "=============================="
        echo We are in $PWD
      env:
        SKIP_TESTS: ${{ inputs.skipTests }}
        DEPLOY_TO_MAVEN: ${{ inputs.deployToMaven }}
        GIT_RELEASE_TAG: ${{ inputs.gitReleaseTag }}

    - name: Condition on boolean (skipTests)
      if: ${{ inputs.skipTests }}
      run: echo Running boolean

    - name: Condition on NEGATED boolean (skipTests)
      if: ${{ ! inputs.skipTests }}
      run: echo Running NEGATED boolean

    - name: Define something here
      if: ${{ !inputs.deployToMaven }}
      run: |
        export MAVE_DEFINED=use_local_repo

    - name: Test env defined somewhere else
      run: echo MAVE_DEFINED is $MAVE_DEFINED

    - name: Build release files
      run: |
        mkdir $GITHUB_WORKSPACE/releaseDist
        set > $GITHUB_WORKSPACE/releaseDist/environ.txt
        echo SPY on SKIP_TESTS = $SKIP_TESTS
        if [ $SKIP_TESTS = "true" ]; then
          echo SKIPPING TESTS
          echo SKIPPING TESTS > $GITHUB_WORKSPACE/releaseDist/skip_tests.txt
        else
          #tmp make check
          echo RUNNING TESTS > $GITHUB_WORKSPACE/releaseDist/tested.txt
          echo RUNNING TESTS
        fi
      env:
        SKIP_TESTS: ${{ inputs.skipTests }}

    - name: Collect artifacts in one folder
      run: |
        pushd releaseDist
        echo Collect artifacts > $GITHUB_WORKSPACE/releaseDist/collect.txt
        popd

    # TODO: add them to the GitHub "Release" page automatically (on condition)
    - name: Upload build results
      uses: actions/upload-artifact@v4.3.6
      with:
        name: test-binaries
        path: ${{ github.workspace }}/releaseDist/
        retention-days: 3 # TBD if we want to keep them longer
        overwrite: true

    - name: Publish to maven
      run: |
        echo "=== $DEPLOY_TO_MAVEN ==="
        echo Publishing to maven
      env:
        DEPLOY_TO_MAVEN: ${{ inputs.deployToMaven }}

    - name: Upload to release
      if: ${{ inputs.gitReleaseTag && startsWith(inputs.gitReleaseTag, 'release-') }}
      run: |
        echo Releasing
        echo ${{ github.workspace }}/releaseDist
        echo ${GITHUB_WORKSPACE}/releaseDist
        pushd ${{ github.workspace }}/releaseDist
        gh release upload ${{ inputs.gitReleaseTag }} * --clobber --repo=${{ github.repository }}
        popd
      env:
        GH_TOKEN: ${{ github.token }}
        GIT_RELEASE_TAG: ${{ inputs.gitReleaseTag }}
