name: A - Test Conditions

on:
  workflow_dispatch:
    inputs:
      skipTests:
        description: 'Skip running the tests.'
        type: boolean
        default: true
      deployToMaven:
        description: 'Deploy to maven'
        type: boolean
        default: false
      gitReleaseTag:
        description: 'Release tag to upload to. Must start with "release-"'
        type: string
      tastsAndMaven:
        description: 'Tests and maven publishing combinations'
        required: true
        default: 'tests_no_maven'
        type: choice
        options:
        - tests_maven
        - tests_no_maven
        - no_tests_maven  # Unsafe, to remove
        - no_tests_no_maven

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release-env

    permissions:
      contents: write
      packages: write

    steps:

    - name: Show input
      run: |
        echo "=============================="
        echo "SKIP_TESTS      : $SKIP_TESTS"
        echo "DEPLOY_TO_MAVEN : $DEPLOY_TO_MAVEN"
        echo "GIT_RELEASE_TAG : $GIT_RELEASE_TAG"
        echo "env.SKIP_TESTS      : ${{ env.SKIP_TESTS }}"
        echo "env.DEPLOY_TO_MAVEN : ${{ env.DEPLOY_TO_MAVEN }}"
        echo "env.GIT_RELEASE_TAG : ${{ env.GIT_RELEASE_TAG }}"
        echo "input skipTests     : ${{ inputs.skipTests }}"
        echo "input deployToMaven : ${{ inputs.deployToMaven }}"
        echo "input gitReleaseTag : ${{ inputs.gitReleaseTag }}"
        echo "GITHUB_SHA  : ${GITHUB_SHA}"
        echo "GITHUB_REF  : ${GITHUB_REF}"
        echo "=============================="
        echo We are in $PWD
      env:
        SKIP_TESTS: ${{ inputs.skipTests }}
        DEPLOY_TO_MAVEN: ${{ inputs.deployToMaven }}
        GIT_RELEASE_TAG: ${{ inputs.gitReleaseTag }}

    - name: Running tests
      if: ${{ ! inputs.skipTests }}
      run: echo Running TESTS

    - name: Build release files
      run: |
        mkdir $GITHUB_WORKSPACE/releaseDist
        set > $GITHUB_WORKSPACE/releaseDist/environ.txt

    - name: Collect artifacts in one folder
      run: |
        pushd releaseDist
        echo Collect artifacts > $GITHUB_WORKSPACE/releaseDist/collect.txt
        popd

    - name: Upload build results
      uses: actions/upload-artifact@v4.3.6
      with:
        name: test-binaries
        path: ${{ github.workspace }}/releaseDist/
        retention-days: 3 # TBD if we want to keep them longer
        overwrite: true

    - name: Publish to maven
      run: |
        if [ "${{ inputs.deployToMaven }}" != "true" ]; then
          export MAVEN_LOCAL='-Durl=this_is_local'
        fi
        echo mvn deploy $MAVEN_LOCAL -DskipTests -DskipITs
        echo Publishing to maven
      env:
        DEPLOY_TO_MAVEN: ${{ inputs.deployToMaven }}

    - name: Upload to release
      if: ${{ inputs.gitReleaseTag && startsWith(inputs.gitReleaseTag, 'release-') }}
      run: |
        echo Releasing
        echo ${{ github.workspace }}/releaseDist
        echo ${GITHUB_WORKSPACE}/releaseDist
        pushd ${{ github.workspace }}/releaseDist
        ls
        echo "gh release upload ${{ inputs.gitReleaseTag }} * --clobber --repo=${{ github.repository }}"
        gh release upload ${{ inputs.gitReleaseTag }} * --clobber --repo=${{ github.repository }}
        popd
      env:
        GH_TOKEN: ${{ github.token }}
        GIT_RELEASE_TAG: ${{ inputs.gitReleaseTag }}
