name: A - Test Conditions

on:
  workflow_dispatch:
    inputs:
      runTests:
        description: 'Run the tests.'
        type: boolean
        default: true
      deployToMaven:
        description: 'Deploy to maven'
        type: boolean
        default: false
      gitReleaseTag:
        description: 'Release tag to upload to. Must start with "release-"'
        type: string
      tastsAndMaven:
        description: 'Tests and maven publishing combinations'
        required: true
        default: 'tests_no_maven'
        type: choice
        options:
        - tests_maven
        - tests_no_maven
        - no_tests_maven  # Unsafe, to remove
        - no_tests_no_maven

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release-env

    permissions:
      contents: write # So that we can upload to release
      packages: write # So that we can store the binaries of this build for a while

    steps:

    - name: Checkout repo files
      uses: actions/checkout@v4.1.7
      with:
        lfs: true

    - name: Show input
      run: |
        echo "=============================="
        echo "RUN_TESTS           : $RUN_TESTS"
        echo "DEPLOY_TO_MAVEN     : $DEPLOY_TO_MAVEN"
        echo "GIT_RELEASE_TAG     : $GIT_RELEASE_TAG"
        echo "env.RUN_TESTS       : ${{ env.RUN_TESTS }}"
        echo "env.DEPLOY_TO_MAVEN : ${{ env.DEPLOY_TO_MAVEN }}"
        echo "env.GIT_RELEASE_TAG : ${{ env.GIT_RELEASE_TAG }}"
        echo "input runTests      : ${{ inputs.runTests }}"
        echo "input deployToMaven : ${{ inputs.deployToMaven }}"
        echo "input gitReleaseTag : ${{ inputs.gitReleaseTag }}"
        echo "GITHUB_SHA  : ${GITHUB_SHA}"
        echo "GITHUB_REF  : ${GITHUB_REF}"
        echo "=============================="
        echo The current folder is $PWD
      env:
        RUN_TESTS: ${{ inputs.runTests }}
        GIT_RELEASE_TAG: ${{ inputs.gitReleaseTag }}

    - name: Running tests
      if: ${{ inputs.runTests }}
      run: echo Running TESTS

    - name: Build release files
      run: |
        mkdir $GITHUB_WORKSPACE/releaseDist
        set > $GITHUB_WORKSPACE/releaseDist/environ.txt

    - name: Collect artifacts in one folder
      run: |
        echo Collect artifacts > $GITHUB_WORKSPACE/releaseDist/collect1.txt
        echo Collect artifacts > ${{ github.workspace }}/releaseDist/collect2.txt

    - name: Upload build results
      # if: false # Temporarily disabled
      uses: actions/upload-artifact@v4.3.6
      with:
        name: test-binaries
        path: ${{ github.workspace }}/releaseDist/
        retention-days: 1 # TBD if we want to keep them longer
        overwrite: true

    - name: Publish to maven
      run: |
        if [ "${{ inputs.deployToMaven }}" != "true" ]; then
          # Run the deploy, but do it to a local folder, not to Sonatype / Maven Central
          export MAVEN_LOCAL='-Durl=this_is_local'
        fi
        echo mvn deploy $MAVEN_LOCAL -DrunTests -DskipITs

    - name: Upload to release
      if: ${{ inputs.gitReleaseTag && startsWith(inputs.gitReleaseTag, 'release-') }}
      run: |
        # pushd ${{ github.workspace }}/releaseDist
        # gh release upload ${{ inputs.gitReleaseTag }} * --clobber --repo=${{ github.repository }}
        # popd
        ls
        gh release upload ${{ inputs.gitReleaseTag }} ${{ github.workspace }}/releaseDist/* --clobber --repo=${{ github.repository }}
      env:
        GH_TOKEN: ${{ github.token }}
